#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_3/MechVars.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_3/MechRamping.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_3/MechSetMotors.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_3/MechAutFuns.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_3/MechUserFuns.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_3/MechAuton.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_3/MechStartUpFuns.cpp"