#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_5/MechVars.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_5/MechRamping.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_5/MechSetMotors.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_5/MechAutFuns.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_5/MechUserFuns.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_5/MechAuton.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_5/MechStartUpFuns.cpp"