#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_1/MechVars.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_1/MechRamping.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_1/MechSetMotors.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_1/MechAutFuns.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_1/MechUserFuns.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_1/MechAuton.cpp"
#include "Z-Team-Repository/2131Z - MPLift/Includes/In_1_1/MechStartUpFuns.cpp"