#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_7/MechVars.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_7/MechRamping.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_7/MechSetMotors.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_7/MechAutFuns.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_7/MechUserFuns.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_7/MechAuton.cpp"
#include "Z-Team-Repository/2131Z - MecPunch/Includes/In_1_7/MechStartUpFuns.cpp"